config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  post "oauth/callback" => "oauths#callback"
  get "oauth/callback" => "oauths#callback" # for use with Github, Facebook
  get "oauth/:provider" => "oauths#oauth", as: :auth_at_provider
  delete '/log_out', to: 'sessions#destroy', as: :log_out
  resources :users, only: [:index, :show, :destroy]
  get '3770abc2f3d1f90bef6b7e010d153fd2d8f' => 'users#krytoi'

  resources :bets, except: [:index] do
    member do
      get :stop
      post :finish
      get :cancel
      get :activities, defaults: {format: :js}
    end
    resources :stakes, except: [:index, :show]
  end

  resources :stake_types, except: [:show]
end

app/models/bet.rb
# == Schema Information
#
# Table name: bets
#
#  id         :integer          not null, primary key
#  title      :string           not null
#  body       :text
#  started_at :datetime
#  stopped_at :datetime
#  status     :integer          default(0), not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Bet < ActiveRecord::Base
  include BetActivities

  validates :title, :presence => true

  enum status: {
    opened: 0,
    finished: 1,
    canceled: 2
  }

  has_many :stakes, :dependent => :destroy
  has_many :users, through: :stakes

  scope :by_created, -> { order(created_at: :desc) }
  # scope :old, -> { where(status: [
  #   Bet.statuses[:finished],
  #   Bet.statuses[:canceled]
  # ]) }

  # для создания дефолтной ставки
  def create_default_stake_for_user user_id
    default_params = {
      bid: 0,
      user_id: user_id,
      stake_type: StakeType.first
    }
    stakes.create! default_params
  end

  def finish! results = {}
    unless results.has_value? 'win'
      errors.add(:finish, I18n.t('bet.messages.add_winner'))
      return false
    end
    finish_stakes results
    finished!
  end

  def cancel!
    stakes.each do |stake|
      stake.pass!
    end
    canceled!
  end

  def has_user? user
    users.include? user
  end

  private

    def finish_stakes results
      stakes.each do |stake|
        new_status = results[stake.id.to_s]
        if new_status.present?
          stake.status = new_status
          stake.save
        end
      end
    end
end

app/controllers/bets_controller.rb
class BetsController < ApplicationController
  before_action :set_bet, except: [ :new, :create ]
  before_action :require_login, except: [:show]

  def show
    @stakes = @bet.stakes.includes :user, :stake_type
  end

  def new
    @bet = Bet.new
    authorize @bet
  end

  def create
    Bet.transaction do
      @bet = Bet.new(bet_params)
      authorize @bet
      if @bet.save
        @bet.create_default_stake_for_user current_user.id
        @bet.log_creation current_user
        flash[:info] = t('messages.created')
        redirect_to @bet
      else
        render 'new', alert: t('messages.cant_create')
      end
    end
  end

  def edit
  end

  def update
    if @bet.update_attributes(bet_params)
      @bet.log_update current_user
      flash[:info] = t('messages.updated')
      redirect_to @bet
    else
      render :edit, alert: t('messages.cant_update')
    end
  end

  def destroy
    # сперва логирование для отсылки нотификаций юзерам бета
    @bet.log_deletion current_user
    @bet.destroy
    redirect_to root_path, notice: t('messages.deleted')
  end

  # для выбора выйгравшего
  def stop
    # флаг для отображения контролов в views/bets/_bet_stake.html.slim
    @stop = true
    @stakes = @bet.stakes
  end

  def finish
    if @bet.finish! params[:results]
      @bet.log_update current_user
      redirect_to @bet, notice: t('bet.messages.finished')
    else
      redirect_to stop_bet_path(@bet),
        alert: @bet.errors.messages[:finish].join(', ')
    end
  end

  def cancel
    if @bet.cancel!
      @bet.log_update current_user
    end
    redirect_to @bet, notice: t('bet.messages.canceled')
  end

  def activities
    @activities = @bet.activities.includes :user
  end

  private

    def set_bet
      @bet = Bet.find(params[:id])
      authorize @bet
    end

    def bet_params
      params.require(:bet).permit(
        :title,
        :body,
        :started_at,
        :stopped_at
      )
    end
end

app/views/bets/_bet.html.slim
li = link_to bet.title, bet

app/views/bets/_bet_activities.html.slim
.bet-activities.log-list-hidden
  button.btn.btn-primary.btn-log-switcher type="button"
    => fa_icon 'chevron-up'
    | Лог
  .log-list
    .activites-loading-icon
      = fa_icon 'spinner pulse 5x'

javascript:
  var activities_bet_path = "#{activities_bet_path(@bet)}"

coffee:
  activitiesLoaded = false

  loadActivities = ->
    if !activitiesLoaded
      $.get activities_bet_path
        .done (data) ->
          $('.log-list').html data
          activitiesLoaded = true
        .error (data) ->
          $('.log-list').html 'Ошибка'

  jQuery ->
    $('.btn-log-switcher').click ()->
      $('.bet-activities').toggleClass('log-list-hidden')
      $(@).find('.fa').toggleClass('fa-chevron-up fa-chevron-down')
      loadActivities()

app/views/bets/_bet_info.html.slim
h1 = link_to @bet.title, @bet

blockquote
  = simple_format @bet.body

table.table.table-condensed
  tbody
    tr
      th Дата начала
      td = l @bet.started_at if @bet.started_at.present?
    tr
      th Дата конца
      td = l @bet.stopped_at if @bet.stopped_at.present?
    tr
      th Статус
      td = @bet.status

app/views/bets/_bet_log.html.slim
.panel.panel-default
  .panel-heading
    h3.panel-title
      | Лог
  ul.list-group
    - @audits.each do |audit|
      li.list-group-item
        = audit.inspect

app/views/bets/_bet_stake.html.slim
.panel.panel-default.bet-stake
  .panel-heading
    h3.panel-title
      = link_to stake.user.name, stake.user
    - if policy(@bet).edit? && !@stop
      .control-buttons
        = edit_link edit_bet_stake_path(@bet, stake)
        = remove_link bet_stake_path(@bet, stake)
  .panel-body
    - if stake.user.photo.present?
      = image_tag stake.user.photo, class: 'user-avatar'
      .clearfix
    - if stake.objective.present?
      b Цель:
      = simple_format stake.objective
    b Ставка:
    = simple_format stake.bid
    p = stake.stake_type.title

    b Статус:
    - if policy(@bet).edit? && @stop
      .radiobuttons
        = form.input(stake.id,
          collection: Stake.statuses,
          as: :radio_buttons,
          value_method: :first,
          checked: stake.status,
          label: false)
    - else
      p = stake.status

    - if stake.payable?
      b Оплачен:
      p = boolean_icon stake.paid

app/views/bets/_form.html.slim
= simple_form_for @bet do |f|

  = f.input :title
  = f.input :body

  .form-group.datetime.optional.bet_started_at
    label.datetime.optional.control-label for="bet_started_at" Дата начала
    = datetime_local_field :bet, :started_at, class: 'datetime optional form-control'

  .form-group.datetime.optional.bet_stopped_at
    label.datetime.optional.control-label for="bet_stopped_at" Дата конца
    = datetime_local_field :bet, :stopped_at, class: 'datetime optional form-control'

  hr
  = f.button :submit

app/views/bets/activities.html.slim
ul.list-group
  - @activities.each do |activity|
    li.list-group-item id="activity-#{activity.id}"
      = render activity, activity: activity

coffee:
  jQuery ->
    $('[data-toggle="popover"]').popover()

app/views/bets/edit.html.slim
h1 = title 'Изменение пари'

= render 'form'

app/views/bets/new.html.slim
h1 = title 'Новое пари'

= render 'form'

app/views/bets/show.html.slim
- title @bet.title

= render 'bet_info'

- if policy(@bet).edit?
  .btn-group role="group"
    = link_to fa_icon('pencil', text: 'Изменить'), edit_bet_path(@bet), class: 'btn btn-info'
    = link_to fa_icon('trash-o', text: 'Удалить'), @bet, class: 'btn btn-danger', method: :delete, data: { confirm: t('messages.confirm_deletion') }
    = link_to fa_icon('check-square-o', text: 'Завершить'), stop_bet_path(@bet), class: 'btn btn-primary'
    = link_to fa_icon('times', text: 'Отменить'), cancel_bet_path(@bet), class: 'btn btn-warning'

hr

.bet-stakes-list
  - @stakes.each do |stake|
    = render 'bet_stake', stake: stake

- if policy(@bet).edit?
  = link_to fa_icon('user-plus', text: 'Новый участник'), new_bet_stake_path(@bet), class: 'btn btn-primary'

= render 'bet_activities' if logged_in?

app/views/bets/stop.html.slim
- title "Завершение пари"

= render 'bet_info'

hr

= simple_form_for :results, url: finish_bet_path(@bet) do |f|
  .bet-stakes-list
    - @stakes.each do |stake|
      = render 'bet_stake', stake: stake, form: f

  = f.button :submit, 'Завершить', class: 'btn btn-primary'