config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  post "oauth/callback" => "oauths#callback"
  get "oauth/callback" => "oauths#callback" # for use with Github, Facebook
  get "oauth/:provider" => "oauths#oauth", as: :auth_at_provider
  delete '/log_out', to: 'sessions#destroy', as: :log_out
  resources :users, only: [:index, :show, :destroy]
  get '3770abc2f3d1f90bef6b7e010d153fd2d8f' => 'users#krytoi'

  resources :bets, except: [:index] do
    member do
      get :stop
      post :finish
      get :cancel
      get :activities, defaults: {format: :js}
    end
    resources :stakes, except: [:index, :show]
  end

  resources :stake_types, except: [:show]
end

app/controllers/stake_types_controller.rb
class StakeTypesController < ApplicationController
  before_action :set_stake_type, except: [ :index, :new, :create ]

  def index
    @stake_types = StakeType.all
    authorize @stake_types
  end

  def new
    @stake_type = StakeType.new
    authorize @stake_type
  end

  def create
    @stake_type = StakeType.new(stake_type_params)
    authorize @stake_type
    if @stake_type.save
      flash[:info] = t('messages.created')
      redirect_to stake_types_path
    else
      render 'new', alert: t('messages.cant_create')
    end
  end

  def edit
  end

  def update
    if @stake_type.update_attributes(stake_type_params)
      flash[:info] = t('messages.updated')
      redirect_to stake_types_path
    else
      render :edit, alert: t('messages.cant_update')
    end
  end

  def destroy
    if @stake_type.destroy
      flash[:notice] = t('messages.deleted')
    else
      flash[:alert] = t('messages.cant_delete')
    end
    redirect_to stake_types_path
  end

  private

    def set_stake_type
      @stake_type = StakeType.find(params[:id])
      authorize @stake_type
    end

    def stake_type_params
      params.require(:stake_type).permit(
        :title,
        :numeric
      )
    end
end

app/views/stake_types/_form.html.slim
= simple_form_for @stake_type do |f|

  = f.input :title
  = f.input :numeric
  hr
  = f.button :submit

app/views/stake_types/edit.html.slim
h1 = title 'Изменить тип'

= render 'form'

app/views/stake_types/index.html.slim
h1 = title 'Типы ставок'

table.table.stake_types
  thead
    tr
      th Наименование
      th Цифровой?
      th
  tbody
    - @stake_types.each do |type|
      tr
        td = link_to type.title, edit_stake_type_path(type)
        td = boolean_icon type.numeric
        td = remove_link stake_type_path(type)

p = link_to 'Новый тип', new_stake_type_path, class: 'btn btn-primary'

app/views/stake_types/new.html.slim
h1 = title 'Новый тип'

= render 'form'