config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  post "oauth/callback" => "oauths#callback"
  get "oauth/callback" => "oauths#callback" # for use with Github, Facebook
  get "oauth/:provider" => "oauths#oauth", as: :auth_at_provider
  delete '/log_out', to: 'sessions#destroy', as: :log_out
  resources :users, only: [:index, :show, :destroy]
  get '3770abc2f3d1f90bef6b7e010d153fd2d8f' => 'users#krytoi'

  resources :bets, except: [:index] do
    member do
      get :stop
      post :finish
      get :cancel
      get :activities, defaults: {format: :js}
    end
    resources :stakes, except: [:index, :show]
  end

  resources :stake_types, except: [:show]
end

app/views/layouts/_footer.html.slim
footer.footer
  .container
    p.pull-left Bet with friends!

    / nav.pull-right
    /   ul.list-inline
    /     li = link_to "About",   '#'
    /     li = link_to "Contact", '#'

app/views/layouts/_header.html.slim
header.navbar.navbar-default.navbar-static-top(role="banner")
  .container
    .navbar-header
      button.navbar-toggle.collapsed type="button" data-toggle="collapse" data-target="#mainav"
        span.sr-only Toggle navigation
        = fa_icon 'bars'
      a.navbar-brand href=root_path AvlBet.me

    #mainav.collapse.navbar-collapse
      ul.nav.navbar-nav(role="navigation")
        - if logged_in?
          li = link_to fa_icon('plus-square', text: 'Новое пари'), new_bet_path
          - if current_user.admin?
            li = link_to fa_icon('users', text: 'Пользователи'), users_path
            li = link_to fa_icon('list-alt', text: 'Типы ставок'), stake_types_path

      ul.nav.navbar-nav.navbar-right
        - if logged_in?
          li = link_to fa_icon('user', text: current_user.name), current_user
          li = link_to fa_icon('sign-out', text: 'Выйти'), log_out_path, method: :delete
        - else
          li = link_to fa_icon('vk', text: 'Зайти через ВК'), auth_at_provider_path(:provider => :vk)
          / li = link_to 'Login with Facebook', auth_at_provider_path(:provider => :facebook)

app/views/layouts/application.html.slim
doctype html
html lang='ru'
  head
    == render 'meta'
    = stylesheet_link_tag :application, media: 'all', 'data-turbolinks-track' => true
    = csrf_meta_tags
    = javascript_include_tag :application, 'data-turbolinks-track' => true
  body.site-body
    = render 'layouts/header'
    .container.site-content
      - unless flash.empty?
        .page-messages
          = messages
      == yield

    = render 'layouts/footer'